#!/usr/bin/env python3
"""Render analysis/reports/detection-ospa.md from analysis/results/detection_ospa.json.

Every table below is generated from the JSON, so the report cannot drift from the run that
produced it. The prose is held here rather than in the markdown for the same reason: one file
to edit, one command to regenerate.

Usage:  python analysis/scripts/detection_ospa_report.py [--overlays <overlay dir>]
"""
import argparse
import json
from pathlib import Path

import sys
sys.path.insert(0, str(Path(__file__).resolve().parent))
from paths import ANALYSIS, RESULTS  # noqa: E402


def latest_overlays():
    root = ANALYSIS / "overlays/detections"
    runs = sorted(p.name for p in root.iterdir() if p.is_dir()) if root.is_dir() else []
    return f"analysis/overlays/detections/{runs[-1]}" if runs else "analysis/overlays/detections/<stamp>"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--json", default=str(RESULTS / "detection_ospa.json"))
    ap.add_argument("--overlays", default=None)
    args = ap.parse_args()
    r = json.loads(Path(args.json).read_text())
    P, CUT = r["params"], r["cutoffs"]
    head = f"{P['headline_cutoff_mm']:g}"
    others = [k for k in CUT if k != head]
    CFG = list(CUT[head])
    overlays = args.overlays or latest_overlays()

    L = []
    w = L.append
    w("# Vessel localisation scored as a detection problem: counts, matching and OSPA")
    w("")
    w("*2026-09-04. Companion to `reports/ours-same-metric-derivations.md` and")
    w("`reports/vessel-centreline-derivations.md`. Generated by `scripts/detection_ospa_report.py`")
    w("from `results/detection_ospa.json`; the numbers are never retyped.*")
    w("")
    w("---")
    w("")
    w("## Why")
    w("")
    w("Every distance on the poster is a mean over things that were assumed to correspond: pixel to")
    w("nearest pixel, centroid to centroid. None of them says how many vessels the model found, and a")
    w("mean over matched objects quietly rewards a model that predicts the one easy vessel and skips")
    w("the hard ones. A frame or a map here holds **0, 1, 2 or 3** vessels, so the task is a detection")
    w("problem, and it is scored the way object detection and multi-target tracking are scored:")
    w("extract objects, match them, then report **counts**, **detection rates** and **localisation")
    w("error** separately, plus one penalised scalar for model selection.")
    w("")
    w("## The metric")
    w("")
    w("Objects are matched with the Hungarian algorithm and scored with **OSPA** (Schuhmacher, Vo &")
    w("Vo, 2008), the standard distance between two sets of different cardinality, with an asymmetric")
    w("cardinality penalty:")
    w("")
    w("```")
    w("d = [ SUM_matched min(d_i, c)  +  c * (a_FP * FP + a_FN * FN) ] / max(m, n)")
    w("```")
    w("")
    w("| parameter | value | where it comes from |")
    w("|---|---|---|")
    w(f"| `c` = `tau` | **{head} mm** | the clinical usefulness threshold: the distance beyond which a localisation is useless here. Set by judgement, not tuned on the data. |")
    w(f"| `a_FP` | **{P['alpha_fp']:.0f}** | a false vessel costs twice a missed one: it sends a needle into tissue, whereas a miss only forfeits the assist. |")
    w(f"| `a_FN` | **{P['alpha_fn']:.0f}** | reference weight. |")
    w(f"| `p` | **{P['p']}** | so OSPA is an average in millimetres. |")
    w("")
    w("`m` = predicted objects, `n` = true objects. Because both weights are >= 1, pairing is never")
    w("dearer than leaving a pair unmatched, so the optimal assignment matches `min(m, n)` objects and")
    w("the cardinality error is `|m - n|`. Two empty sets score 0; the metric is bounded above by")
    w(f"`max(a_FP, a_FN) * c` = **{max(P['alpha_fp'], P['alpha_fn']) * float(head):g} mm**, the score of a data point that is all false alarms.")
    w("")
    w(f"The cutoff was **1 mm** when this was first written (the error margin for IV needle access)")
    w(f"and was raised to **{head} mm** by the user on 2026-09-04. Both are reported below rather than")
    w("only the current one, because the choice of `c` is a judgement and it moves every number.")
    w("")
    w("Reported **beside** OSPA, never instead of it, because OSPA alone cannot separate a")
    w("localisation error from a detection error: the count confusion matrix, precision / recall / F1")
    w("at `tau`, and the mean distance over matched pairs.")
    w("")
    w("## Extraction")
    w("")
    w("Two object types, because \"where is the vessel\" has two natural answers:")
    w("")
    w("* **centreline** --- one straight segment per vessel, total-least-squares fit. Distance between")
    w("  two centrelines is the symmetric mean point-to-segment distance (25 samples per segment).")
    w("* **centroid** --- one point per vessel. Distance is plain Euclidean, in mm.")
    w("")
    w("...and two spaces, which differ in what is on disk:")
    w("")
    w("* **Video-frame space** carries the model's **per-marker probabilities** (`probs` in the saved")
    w("  npz, 0.10--0.999), so the prediction side uses a **heatmap head**: non-maximum suppression over")
    w("  the score field picks peaks, every above-threshold marker joins its nearest peak, and each")
    w("  object's centroid and axis are **score-weighted**, which localises below the ~2 mm marker")
    w("  pitch. Plain radial NMS would shred an elongated vessel into one object per bump, so a peak is")
    w(f"  only allowed to split a connected component when the peaks are more than `R_SPLIT` = {P['r_split_mm']:.1f} mm")
    w(f"  apart **and** the score dips below {P['valley_frac']:.2f} x the weaker peak between them --- a watershed in spirit.")
    w("  `R_SPLIT` sits below the smallest true vessel separation in the data (3.5 mm) and above the")
    w("  marker pitch (1.8--2.0 mm).")
    w("* **Top-view map space** has only the thresholded masks on disk --- no probability map is saved by")
    w("  the map builder --- so extraction there is plain connected components with an unweighted")
    w("  centroid and axis, and **no heatmap head is used**.")
    w("")
    w(f"Near-duplicates are merged in both spaces so a fragmented mask cannot over-count: centroids")
    w(f"closer than {P['merge_mm']:.0f} mm, or centrelines within {P['merge_ang_deg']:.0f} deg of each other, offset by less than {P['merge_mm']:.0f} mm")
    w(f"**and overlapping along their shared axis**. That last clause matters: without it the silicone")
    w("phantom's left- and right-hand sweeps of the same row, which are collinear but disjoint, were")
    w("fused into one object and the ground-truth count came out as 8 instead of 10.")
    w("")
    w("### The extraction is validated against physical ground truth")
    w("")
    w("The recovered **ground-truth** object count is right on every top-view trial, for both object")
    w("types:")
    w("")
    w("| map | recovered | physically present |")
    w("|---|---|---|")
    w("| Sim->Sim, whole map | 1 | 1 simulated vein |")
    w("| Sim->Silicone / Meat->Silicone, whole map | 10 | \"silicone phantom, ten sweeps\" (`run.json`) |")
    w("| Sim->Meat trials 01--07 | 1 each | `1-metal-straw-...`, `1-silicone-straw-...` |")
    w("| Sim->Meat trial 08 | 2 | `2-metal-straws-beneath-2-steaks` |")
    w("| Sim->Meat trial 09 | 3 | `3-metal-straws-beneath-2-steaks` |")
    w("| Sim->Meat trial 10 | 0 | `no-straw` |")
    w("")
    w("---")
    w("")
    w(f"## Results at c = tau = {head} mm")
    w("")
    for kind in ("centreline", "centroid"):
        w(f"### {kind.capitalize()}s")
        w("")
        w("| config | space | n | count acc. | count MAE | P | R | F1 | matched-pair mean | within `tau` | **OSPA** |")
        w("|---|---|---|---|---|---|---|---|---|---|---|")
        for name in CFG:
            for sp, lab in (("frame", "video frame"), ("top_view", "top-view map")):
                s = CUT[head][name][kind][sp]
                mm = "--" if s["matched_mean_mm"] is None else f"{s['matched_mean_mm']:.2f} mm (n={s['matched_n']})"
                hm = "--" if s["hit_mean_mm"] is None else f"{s['hit_mean_mm']:.2f} mm (n={s['hit_n']})"
                w(f"| {name} | {lab} | {s['n_points']} | {s['count_accuracy']:.2f} | {s['count_mae']:.2f} | "
                  f"{s['precision']:.2f} | {s['recall']:.2f} | {s['f1']:.2f} | {mm} | {hm} | **{s['ospa_mean_mm']:.2f} mm** |")
        w("")

    w("### How the cutoff moves the answer")
    w("")
    w("Video-frame space, centrelines. `c` scales OSPA, so the values are not comparable across")
    w("columns; the **ordering** is, and it is the same at both cutoffs.")
    w("")
    w("| config | " + " | ".join(f"F1 @ {k} mm" for k in [head] + others) +
      " | " + " | ".join(f"OSPA @ {k} mm" for k in [head] + others) + " |")
    w("|---" * (1 + 2 * (1 + len(others))) + "|")
    for name in CFG:
        f1s = [f"{CUT[k][name]['centreline']['frame']['f1']:.2f}" for k in [head] + others]
        os_ = [f"{CUT[k][name]['centreline']['frame']['ospa_mean_mm']:.2f} mm" for k in [head] + others]
        w(f"| {name} | " + " | ".join(f1s) + " | " + " | ".join(os_) + " |")
    w("")
    w("### OSPA split by whether a vessel is actually there (video-frame space, centrelines)")
    w("")
    w("A vessel-free data point scores 0 when the model also says \"nothing\", and Sim->Sim has 379 of")
    w("them, which flatters its pooled mean. Split out:")
    w("")
    w("| config | all frames | vessel-bearing | vessel-free |")
    w("|---|---|---|---|")
    for name in CFG:
        s = CUT[head][name]["centreline"]["frame"]
        vf = "--" if s["ospa_mean_vessel_free_mm"] is None else f"{s['ospa_mean_vessel_free_mm']:.2f} mm (n={s['n_vessel_free']})"
        w(f"| {name} | {s['ospa_mean_mm']:.2f} mm (n={s['n_points']}) | "
          f"{s['ospa_mean_vessel_present_mm']:.2f} mm (n={s['n_vessel_present']}) | {vf} |")
    w("")
    w("### Count confusion, video-frame space, centrelines (rows = true count, columns = predicted)")
    w("")
    w("Counts do not depend on the cutoff.")
    w("")
    for name in CFG:
        c = CUT[head][name]["centreline"]["frame"]["count_confusion_gt_by_pred"]
        w(f"**{name}**")
        w("")
        w("| true \\ pred | 0 | 1 | 2 | 3 | 4+ |")
        w("|---|---|---|---|---|---|")
        for i, row in enumerate(c):
            if sum(row) == 0:
                continue
            w(f"| **{i if i < 4 else '4+'}** | " + " | ".join(str(v) for v in row) + " |")
        w("")

    w("---")
    w("")
    w("## Pictures of the final matched state")
    w("")
    w(f"`scripts/detection_overlays.py` draws one image per data point showing **exactly the objects")
    w(f"scored above**, after filtering and after matching --- no candidate peaks, no pre-merge")
    w(f"fragments. Current run: **`{overlays}`**")
    w("(3465 images, 179 MB, `tau` = " + head + " mm).")
    w("")
    w("| style | meaning |")
    w("|---|---|")
    w("| magenta / orange | ground truth / prediction |")
    w("| solid, label `k` | matched pair, within the tolerance |")
    w("| solid thin, label `k*` | matched pair, but farther apart than the tolerance |")
    w("| dashed line, hollow dot, label `(k)` | **unmatched** object |")
    w("")
    w("A magenta `k` and an orange `k` are the same pair; an index that appears in only one colour is")
    w("unmatched. Markers and pixels keep the confusion colours (TP green, FN red, FP blue, TN grey),")
    w("and every title lists the pair distances and that data point's OSPA. Three variants per data")
    w("point: `centreline/`, `centroid/`, and `both/` (the centreline objects with their segment and")
    w("their centroid drawn together, matched as centrelines). The bulk frame-space images and the")
    w("contact sheets are git-ignored; the top-view images and the manifests are tracked.")
    w("")
    # ------------------------------------------------------------------ interpretation
    F = {n: CUT[head][n]["centreline"]["frame"] for n in CFG}
    M = {n: CUT[head][n]["centreline"]["top_view"] for n in CFG}
    ss, sb, sm, mb = CFG
    hi = max(P["alpha_fp"], P["alpha_fn"]) * float(head)
    w("---")
    w("")
    w("## What the numbers say")
    w("")
    w("**OSPA orders the four transfers, and it is the first single number on this project that")
    w("does.** Video-frame space, centrelines: " +
      ", ".join(f"{n} **{F[n]['ospa_mean_mm']:.2f}**" for n in CFG) + " mm; F1 at the same")
    w("tolerance runs " + " / ".join(f"{F[n]['f1']:.2f}" for n in CFG) + " in the same order. The")
    w("poster's distance columns do not order them this way, because they never charge for a vessel")
    w("that was invented or missed.")
    w("")
    w(f"**{ss} is the one configuration that works.** Its top-view map finds exactly one vessel where")
    w(f"there is exactly one, at {M[ss]['ospa_mean_mm']:.2f} mm, with precision, recall and F1 all {M[ss]['f1']:.2f}. Per frame it holds")
    w(f"up too: {F[ss]['tp']} true detections against {F[ss]['fp']} false alarms and {F[ss]['fn']} misses "
      f"(P {F[ss]['precision']:.2f}, R {F[ss]['recall']:.2f}), and")
    w(f"the pairs it does make sit {F[ss]['hit_mean_mm']:.2f} mm apart on average.")
    w("")
    w(f"**Detection degrades faster than localisation.** On {sb} the model still finds most vessels")
    w(f"(F1 {F[sb]['f1']:.2f} per frame) but its OSPA is {F[sb]['ospa_mean_mm']:.2f} mm; by {mb} F1 is {F[mb]['f1']:.2f} and OSPA {F[mb]['ospa_mean_mm']:.2f} mm.")
    w(f"Count accuracy tells the same story: " + " -> ".join(f"{F[n]['count_accuracy']:.2f}" for n in CFG) +
      ". The confusion matrices show where it goes ---")
    w(f"{sm} and {mb} over-predict, splitting one vessel into two or three, or inventing them where the")
    w("ground truth is empty.")
    w("")
    w("**The matched-only distance is not a metric on its own, and the silicone map proves it.** There")
    w(f"the mean over all matched pairs is **{M[sb]['matched_mean_mm']:.2f} mm**: with 10 true sweeps and 13 predicted objects,")
    w("the Hungarian assignment pairs a sweep at one end of the phantom with one at the other. Restrict")
    w(f"to pairs inside the tolerance and it falls to {M[sb]['hit_mean_mm']:.2f} mm over {M[sb]['hit_n']} pairs --- a different quantity")
    w("entirely. Both are in the tables above so the gap is visible.")
    w("")
    w("**The asymmetric penalty does the work it was asked to do.** " +
      f"{mb}'s {F[mb]['n_vessel_free']} vessel-free frames score")
    w(f"OSPA **{F[mb]['ospa_mean_vessel_free_mm']:.2f} mm** --- the maximum the metric can take, `max(a_FP, a_FN) * c` = {hi:g} mm --- because")
    w("every one of them contains a false alarm and a false alarm is charged twice a miss. That is the")
    w("100 % false-alarm rate, which the poster keeps as spoken material, produced by the metric itself.")
    w("")
    w("**Raising the cutoff from 1 mm to " + head + " mm changes the verdict from \"nothing works\" to \"one")
    w("thing works and the rest are noisy\".** At 1 mm almost no pair survived the gate, so every")
    w("detection rate was near zero and OSPA was dominated by the cardinality term; at " + head + " mm the")
    w("detection rates become informative and the localisation error starts to matter. Neither cutoff")
    w("is more correct --- 1 mm is the needle-access margin, " + head + " mm is nearer a vessel diameter --- which")
    w("is why both are in the table above.")
    w("")
    w("## Caveats")
    w("")
    w("* **This is a heatmap head bolted onto a segmentation head, not a trained one.** The saved")
    w("  per-marker probabilities are used as the score field, which is the right thing to do with what")
    w("  is on disk, but a model trained to regress a Gaussian at each vessel would give points directly")
    w("  instead of inheriting segmentation errors non-linearly. Changing that is a model-design change")
    w("  and a retraining job, not a metric recomputation.")
    w("* **Top-view space gets no heatmap head at all**, because the map builder saves only thresholded")
    w("  masks. It holds a float `maxprob` map in memory (`vessel_map.py::MapData.maxprob`) and discards")
    w("  it. Saving it would let the same extraction run there, and would very likely improve the")
    w("  top-view counts, where the silicone map over-counts 10 true sweeps as 13.")
    w("* **OSPA scales with `c`.** An absolute value is not \"the system is 5 mm accurate\"; it is a")
    w("  blend of localisation error and cardinality error on a scale set by the cutoff. Read the")
    w("  ordering and the F1 column, not the millimetres alone.")
    w("* **The `R_SPLIT` = 3.0 mm splitting rule is data-dependent.** It works because the smallest true")
    w("  vessel separation in these datasets is 3.5 mm. A dataset with vessels closer than that would")
    w("  need the rule re-derived, or a proper watershed on a distance transform.")
    w("")
    w("## Reproduction")
    w("")
    w("```bash")
    w("python analysis/scripts/detection_ospa.py         # analysis/results/detection_ospa.json  (~4 min)")
    w("python analysis/scripts/detection_ospa_report.py  # this file")
    w("python analysis/scripts/detection_overlays.py     # the overlays  (~7 min, 3465 images)")
    w("```")
    w("")
    w("`detection_ospa.py --cutoffs 5 1` sets the cutoffs; `detection_overlays.py")
    w("--tau 5` sets the one the pictures are drawn at. All parameters are recorded in the JSON's")
    w("`params` block and in each overlay run's `params.json`.")
    w("")
    w("## Quotable summary")
    w("")
    w("One sentence, for a caption or an abstract:")
    w("")
    w(f"> Scored as a detection problem at a {head} mm tolerance (OSPA, false alarms weighted twice")
    w("> misses): " + ", ".join(f"{n} {F[n]['ospa_mean_mm']:.2f} mm" for n in CFG) + ".")
    w(f"> {ss} is the only configuration whose top-view map achieves perfect detection")
    w(f"> (F1 = {M[ss]['f1']:.2f}) inside that tolerance.")
    w("")
    out = ANALYSIS / "reports/detection-ospa.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(L) + "\n")
    print(f"written {out} ({len(L)} lines, cutoff {head} mm)")


if __name__ == "__main__":
    main()
