#!/usr/bin/env python3
"""The poster's colour code for the four ML models -- the single source of truth.

The user's rule (2026-09-04): the four models are told apart by INTENSITY of one green,
light for Sim->Sim through dark for Meat->Silicone, and the same four colours are used
wherever a model appears -- table cells, bar charts, the workflow grid's column headers,
the precision-recall panels. The legend for the code lives in ONE place, the caption of
the "Comparison against baselines" table; no other block repeats it.

The ramp is even in CIE L* (88, 70, 52, 34) along a single green hue, so the four steps
are equally spaced to the eye and their order reads as an order. Checked with the dataviz
validator: adjacent normal-vision dE 15.4 and CVD dE 15.2 both pass. The two categorical
checks it also runs (lightness band, chroma floor) are failed BY DESIGN -- they exist to
stop a categorical palette being built as a lightness ramp, which is exactly what was
asked for here -- and its contrast warning is relieved the way the validator itself
allows, by every bar and every table stripe carrying its own printed number.

Text on the two light steps is black; on the two dark steps it is white.

Run `python analysis/scripts/model_colours.py` to print the \\definecolor block that the poster source
carries, so the two cannot drift apart.
"""

# Ordered light -> dark, which is also the poster's model order everywhere.
MODELS = [
    # key,       poster label,       LaTeX colour name, hex,       white text?
    ("A-to-A", "Sim->Sim", "MdlA", "#C6E5C1", False),
    ("A-to-B", "Sim->Silicone", "MdlB", "#7ABA75", False),
    ("A-to-C", "Sim->Meat", "MdlC", "#408C40", True),
    ("C-to-B", "Meat->Silicone", "MdlD", "#205C22", True),
]

# Convenience views. COLOURS is in the poster's model order, so a bar chart can simply do
# `color=COLOURS[i]` for its i-th group.
COLOURS = [hex_ for _, _, _, hex_, _ in MODELS]
BY_KEY = {k: hex_ for k, _, _, hex_, _ in MODELS}
BY_LABEL = {lab: hex_ for _, lab, _, hex_, _ in MODELS}


def definecolor_block():
    """The xcolor definitions the poster source uses, as a string."""
    lines = ["% GENERATED by analysis/scripts/model_colours.py -- keep in step with it.",
             "% The four ML models, told apart by intensity of one green (light Sim->Sim to",
             "% dark Meat->Silicone). Legend: the caption of the baselines table, and nowhere else."]
    for _, label, name, hex_, white in MODELS:
        lines.append(f"\\definecolor{{{name}}}{{HTML}}{{{hex_[1:]}}}   % {label}"
                     f"{', white text' if white else ''}")
    return "\n".join(lines)


if __name__ == "__main__":
    print(definecolor_block())
