np.savez(
    output_path,
    markers=sim_format_data.markers,
    markers_mask=sim_format_data.markers_mask,
    vein_polyline=sim_format_data.vein_polyline,
    vein_polyline_mask=sim_format_data.vein_polyline_mask,
    poses=dilated_data.output,
    metadata=dilated_data.metadata,
)