#!/usr/bin/env bash
#
# Build the Zenodo data bundle (author-side script — users do not run this).
#
# Collects only the artifacts that cannot be regenerated by the repository's own
# scripts, plus the simulated dataset (generable, but ~1 h of GPU time, so it is
# shipped for convenience). See data/MANIFEST.md for the full rationale.
#
# Usage:
#   ./data/make_data_bundle.sh [SOURCE_DIR] [OUTPUT_TAR]
#
#   SOURCE_DIR   Repository-shaped tree holding the full data (defaults to the
#                original submission-state archive on the author's machine).
#   OUTPUT_TAR   Destination .tar.gz (default: ./difftactile-data.tar.gz)
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

SOURCE_DIR="${1:-/home/psb120/Documents/phd/data/masters/diff-tactile-fork-IROS-submission-state/diff-tactile-fork}"
OUTPUT_TAR="${2:-${REPO_DIR}/difftactile-data.tar.gz}"

if [ ! -d "${SOURCE_DIR}" ]; then
    echo "ERROR: source tree not found: ${SOURCE_DIR}" >&2
    exit 1
fi

STAGE="$(mktemp -d)"
trap 'rm -rf "${STAGE}"' EXIT
BUNDLE="${STAGE}/difftactile-data"
mkdir -p "${BUNDLE}"

echo "Source: ${SOURCE_DIR}"
echo "Staging in: ${BUNDLE}"
echo

# copy_tree <relative-path> [find-filter...]
# Copies SOURCE_DIR/<rel> to BUNDLE/<rel>, preserving layout. Extra args are
# passed to `find` so we can ship only the file types actually consumed.
copy_tree() {
    local rel="$1"; shift
    local src="${SOURCE_DIR}/${rel}"
    if [ ! -e "${src}" ]; then
        echo "  MISSING (skipped): ${rel}" >&2
        return 0
    fi
    mkdir -p "${BUNDLE}/${rel}"
    if [ "$#" -gt 0 ]; then
        # Selective copy: only files matching the filter.
        (cd "${src}" && find . -type f \( "$@" \) -print0) \
            | (cd "${src}" && tar --null -T - -cf -) \
            | (cd "${BUNDLE}/${rel}" && tar -xf -)
    else
        cp -r "${src}/." "${BUNDLE}/${rel}/"
    fi
    echo "  added: ${rel}  ($(du -sh "${BUNDLE}/${rel}" | cut -f1))"
}

copy_file() {
    local rel="$1"
    local src="${SOURCE_DIR}/${rel}"
    if [ ! -e "${src}" ]; then
        echo "  MISSING (skipped): ${rel}" >&2
        return 0
    fi
    mkdir -p "${BUNDLE}/$(dirname "${rel}")"
    cp "${src}" "${BUNDLE}/${rel}"
    echo "  added: ${rel}  ($(du -sh "${BUNDLE}/${rel}" | cut -f1))"
}

echo "[1/4] Simulated training dataset (~245 MB)"
copy_tree "difftactile/output/training_data/pickle_20250901_220921_reordered_dense"

echo "[2/4] Real experimental data"
# Silicone: only the final _dense stage is consumed by the GNN.
copy_tree "difftactile/manual_or_experimental_data/endgame/20250901-131547_dense"
# Meat: training reads only the two .npz per trial; the marker_labels.avi
# overlays (81 MB) are visualisation and are deliberately excluded.
copy_tree "difftactile/manual_or_experimental_data/iros_training_data/clean" -name '*.npz'

echo "[3/4] Trained checkpoints"
copy_file "saved_models_icra/final_segmentation_model_gnn_icra.pt"
copy_file "saved_models_iros/final_segmentation_model_gnn_iros.pt"

echo "[4/5] Small artifacts required by the ML entrypoints"
copy_file "difftactile/output/test_loader_gnn_icra.pickle"
copy_file "difftactile/output/test_loader_gnn_iros.pickle"

echo "[5/5] Sensor geometry / marker layout (~5 MB)"
# Derived from the sensor CAD and a reference photo of the undeformed sensor.
# Regenerable in principle (gmsh mesh generation + marker detection), but they
# are small, they never change, and every simulator run needs them - shipping
# them removes a long chain of setup steps before the simulator will start.
copy_file "difftactile/output/base-graph-connectivity.npz"
copy_file "difftactile/output/iros_marker_locations_ordered.npz"
copy_file "difftactile/output/init-marker-positions.npz"
copy_file "difftactile/output/init-marker-positions.pkl"
copy_file "difftactile/output/gmsh_mesh_vitactip.pkl"
copy_file "difftactile/output/gmsh_mesh_vein.pkl"
copy_file "difftactile/output/vitactip_mesh.npz"
copy_file "difftactile/output/edge_lengths.pkl"
copy_file "difftactile/output/tactile_sensor.f2v.pkl"
copy_file "difftactile/output/phantom_points.npz"
copy_file "difftactile/output/vein_points.npz"
copy_file "difftactile/output/is_fixed_layer.npz"
copy_file "difftactile/output/grid_node_v0_mask.npz"
copy_file "difftactile/output/initial_vertex_positions_undeformed.pkl"
copy_file "difftactile/output/vitactip_points_E.pkl"
# System-identification marker tracks: the simulator loads these at start-up to
# align its contact model against the real sensor (main.py load_system_identification_data).
copy_tree "difftactile/output/marker_tracker/domain-adaptation-vascular-markers"

# Ship the manifest and the restore script inside the archive too, so the
# download is self-describing even if separated from the repository.
cp "${SCRIPT_DIR}/MANIFEST.md" "${BUNDLE}/MANIFEST.md" 2>/dev/null || true
cp "${SCRIPT_DIR}/restore_data.sh" "${BUNDLE}/restore_data.sh" 2>/dev/null || true

echo
echo "Bundle contents: $(du -sh "${BUNDLE}" | cut -f1)"
echo "Compressing to ${OUTPUT_TAR} ..."
tar -czf "${OUTPUT_TAR}" -C "${STAGE}" difftactile-data

echo
echo "Done: ${OUTPUT_TAR}  ($(du -sh "${OUTPUT_TAR}" | cut -f1))"
echo "SHA256:"
sha256sum "${OUTPUT_TAR}"
